### ISSUE TITLE
error: duplicate value for resource 'attr/waveOffset' with config ''.

### ISSUE THREAD

**Issue by yangfeng1994** [CarGuo/GSYRecordWave#51]
在AndroidX 中导入 error: duplicate value for resource 'attr/waveOffset' with config ''. 报这个错，里面也用到了GsyVideoPlaer

**Comment by yangfeng1994** [comment]
可以更新一下啦，现在这个用的挺多的。

**Comment by CarGuo** [comment]
太久没关注了，我记一下

**Comment by CarGuo** [comment]
implementation 'com.github.CarGuo:GSYRecordWave:2.0.1'

修改了下项目名，调整了项目支持 androidx
