### ISSUE TITLE
过分，要付费入群

### ISSUE THREAD

**Issue by OneGreenHand** [CarGuo/GSYRecordWave#53]
过分诶，想问个问题，就要付费

**Comment by CarGuo** [comment]
？？？

**Comment by OneGreenHand** [comment]
@CarGuo 不是有个交流群吗底部，要付费入群诶，留下了没技术的泪水

**Comment by CarGuo** [comment]
issue 不就是用来问的么···

**Comment by OneGreenHand** [comment]
@CarGuo 大佬，问下，不是很清楚LameUtil这个类，
System.loadLibrary("mp3lame")这个是加载so库把，我按照和你一样的方法写的，然后LameUtil.init()方法就会报错，
  java.lang.UnsatisfiedLinkError: No implementation found for void com.frame.support.audio.LameUtil.init(int, int, int, int, int) (tried Java_com_frame_support_audio_LameUtil_init and Java_com_frame_support_audio_LameUtil_init__IIIII)

**Comment by CarGuo** [comment]
这是jni 的问题，调用包名比较和so中定义的一致

**Comment by OneGreenHand** [comment]
@CarGuo 那应该怎么解决啊

**Comment by CarGuo** [comment]
应该百度 Android JNI 开发

**Comment by OneGreenHand** [comment]
@CarGuo 谢谢大神，解决了，我建了一个和你的一模一样的包
