### ISSUE TITLE
混合播放音频

### ISSUE THREAD

**Issue by blueYufisher** [CarGuo/GSYRecordWave#54]
请问有方法可以同时既可以播放在线音乐，也可以播放录音文件，就像混音一样？苦恼了很久，完全没有头绪，特意请教一下大神。

**Comment by CarGuo** [comment]
我以前做过，类似于播放的时候，通过 audioTrach ，对 pcm 数据进行 + 处理

**Comment by blueYufisher** [comment]
是audioTrack吗？刚开始接触audioTrack，请问有相关混合音频的项目或文章可以推荐一下吗？
